# Generated by Django 3.0.6 on 2020-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200527_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_system1',
            name='id_personal_category_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
