# Generated by Django 3.0.6 on 2020-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200527_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_system1',
            name='date',
            field=models.DateField(default='2000-03-14'),
        ),
    ]
