# Generated by Django 3.0.6 on 2020-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_income_category_income_system_personal_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_income_category',
            name='person_category_name',
            field=models.CharField(max_length=50),
        ),
    ]
