# Generated by Django 3.0.6 on 2020-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200528_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_cost_category',
            name='person_category_name',
            field=models.CharField(max_length=50),
        ),
    ]
