# Generated by Django 3.0.6 on 2020-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200528_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_cost_category',
            name='person_category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
