# Generated by Django 3.0.6 on 2020-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200528_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_income_category',
            name='person_category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
