# Generated by Django 3.0.6 on 2020-07-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200528_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_cost_category',
            name='person_category_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_income_category',
            name='person_category_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
